### ISSUE TITLE
Cannot find various files during cmake

### ISSUE THREAD

**Issue by ghost** [Pro/open62541-arduino#1]
I get an error during execute cmake command, that some files or directories are missing
![grafik](https://user-images.githubusercontent.com/34797088/38950424-c5cbbece-4345-11e8-863a-728dec666ca9.png)
Have you any idea, what does cause this problem?

**Comment by Pro** [comment]
I'm not sure where these linker flags come from on your system. Could it be from other installed packages?

You can try to build it on a cleanly checked out folder. Have a look at my travis file which compiles the stack for every commit:
https://github.com/Pro/open62541-arduino/tree/master/tools/travis

Otherwise you can try in a clean VM.

Which OS are you using?

**Comment by Pro** [comment]
Since there was no update, I will close this.
